services:
  database:
    image: postgres:16-alpine
    container_name: campground-db-prod
    ports:
      # Use port 5433 on the host to avoid conflicts with local dev setup
      - "5432:5432"
    volumes:
      - campground-db-data-prod:/var/lib/postgresql/data
    env_file: ".env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile.prod
    container_name: campground-api-prod
    ports:
      - "3001:3001"
    env_file: ".env"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?schema=public
      - PORT=3001
      - NODE_ENV=production
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile.prod
    container_name: campground-web-prod
    ports:
      # Map to standard HTTP/S ports
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - api
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: campground-certbot-prod
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    # The command will run in a loop to check for renewal every 12 hours
    command: 'renew --quiet'

  # seeder:
  #   build:
  #     context: .
  #     dockerfile: packages/api/Dockerfile.prod
  #   container_name: campground-seeder-prod
  #   command: sh -c "while true; do echo '--- Seeder: Waiting for 1 hour before next seed. ---'; sleep 3600; echo '--- Seeder: Starting database seed. ---'; node packages/api/prisma/seed.js; done"
  #   env_file: ".env"
  #   depends_on:
  #     - api
  #     - database
  #   environment:
  #     - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?schema=public
  #     - NODE_ENV=production
  #   restart: unless-stopped

volumes:
  campground-db-data-prod: 